stages:
  - build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build-uaffront-uat:
  stage: build
  image: docker:19.03.15
  services:
    - name: docker:19.03.15-dind
      command: ["--mtu=1410"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f Dockerfile -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  environment:
    name: uat
    kubernetes:
      namespace: gitlab-runner
  only:
    - uat
  tags:
    - k8s-stg-runner

deploy-uaffront-uat:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl --kubeconfig="$KUBE_CONFIG" set image deployment/uaffront-deploy uaffront=$TAG_COMMIT -n uaffront-uat
  environment:
    name: uat
    kubernetes:
      namespace: uaffront-uat
  only:
    - uat
  tags:
    - k8s-stg-runner
  when: manual

  
build-uaffront-prd:
  stage: build
  image: docker:19.03.15
  services:
    - name: docker:19.03.15-dind
      command: ["--mtu=1410"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f Dockerfile -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  environment:
    name: master
    kubernetes:
      namespace: gitlab-runner
  only:
    - master
  tags:
    - k8s-stg-runner

deploy-uaffront-prd:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl --kubeconfig="$KUBE_CONFIG" set image deployment/uaffront-deploy uaffront=$TAG_COMMIT -n uaffront-prd
  environment:
    name: master
    kubernetes:
      namespace: uaffront-prd
  only:
    - master
  tags:
    - k8s-stg-runner
  when: manual
